/*
 * Automatically generated by jrpcgen 1.0.5 on 22/04/08 9:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package bamboo.dht;
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * Enumeration (collection of constants).
 */
public interface bamboo_stat {

    public static final int BAMBOO_OK = 0;
    public static final int BAMBOO_CAP = 1;
    public static final int BAMBOO_AGAIN = 2;

}
// End of bamboo_stat.java
