/*
 * Automatically generated by jrpcgen 1.0.5 on 22/04/08 9:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package bamboo.dht;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class bamboo_get_res implements XdrAble {
    public bamboo_value [] values;
    public bamboo_placemark placemark;

    public bamboo_get_res() {
    }

    public bamboo_get_res(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = values.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { values[$idx].xdrEncode(xdr); } }
        placemark.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = xdr.xdrDecodeInt(); values = new bamboo_value[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { values[$idx] = new bamboo_value(xdr); } }
        placemark = new bamboo_placemark(xdr);
    }

}
// End of bamboo_get_res.java
