/*
 * Automatically generated by jrpcgen 1.0.5 on 22/04/08 9:17
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package bamboo.dht;
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * A collection of constants used by the "gateway_prot" ONC/RPC program.
 */
public interface gateway_prot {
    public static final int BAMBOO_DHT_PROC_NULL_3 = 1;
    public static final int BAMBOO_DHT_PROC_NULL_2 = 1;
    public static final int BAMBOO_DHT_GATEWAY_VERSION = 2;
    public static final int BAMBOO_DHT_PROC_PUT_3 = 2;
    public static final int BAMBOO_DHT_PROC_PUT_2 = 2;
    public static final int BAMBOO_DHT_PROC_GET_3 = 3;
    public static final int BAMBOO_DHT_PROC_GET_2 = 3;
    public static final int BAMBOO_DHT_PROC_RM_3 = 4;
    public static final int BAMBOO_DHT_GATEWAY_VERSION_3 = 3;
    public static final int BAMBOO_DHT_GATEWAY_PROGRAM = 708655600;
}
// End of gateway_prot.java
